run:
  tests: true
linters:
  enable-all: true
  disable:
    - contextcheck
    - cyclop
    - exhaustivestruct
    - funlen
    - goerr113
    - ireturn
    - maligned
    - wrapcheck
    - varnamelen
