builds:
  - main: ./cmd/kubectl-fuzzy/kubectl-fuzzy.go
    binary: kubectl-fuzzy
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X github.com/d-kuro/kubectl-fuzzy/pkg/cmd.Revision={{ .ShortCommit }}
checksum:
  name_template: checksums.txt
archives:
  - format: tar.gz
snapshot:
  name_template: master
changelog:
  filters:
    exclude:
      - "Merge pull request"
      - "Merge branch"
release:
  github:
    owner: d-kuro
    name: kubectl-fuzzy
